site_name: 2n DAM Semipresencial - Programació de Serveis i Processos 
docs_dir: "md"
site_dir: "docs"
site_description: "2n DAM Semipresencial - Programació de Serveis i Processos > Sockets"
site_url: https://eniclos.github.io/Sockets/
repo_name: eniclos/Sockets
copyright: "© 2025 Enrique Niclós Camarasa"

theme:
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
          icon: material/brightness-7 
          name: Canvia a mode oscur
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
          icon: material/brightness-4
          name: Canvia a mode clar
      primary: indigo
      accent: indigo

extra_templates:
  - md/index.html

plugins:
  - search
  - page-to-pdf

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - index.md
  - Teoria: 
    - Introducció: teoria/Introduccio.md
    - Multicast TCP: teoria/MulticastUDP.md
    - Resolució DNS: teoria/ResolucioDNS.md
    - Sockets TCP: teoria/SocketsTCP.md
  - Practiques:
    - Tasques: practiques/tasques.md
    
